# Site settings
title: Pixyll
email: your_email@example.com
author: John Otander
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl: ""
url: "http://pixyll.com"
google_analytics: UA-53548208-1

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
